### ISSUE TITLE
retrieving stuffs from r

### ISSUE THREAD

**Issue by ungentilgarcon** [topogram/topogram-api-client#4]
it is more:

topogram_id = r['data'][0]['_id']
rather than 
r['data']['_id']

**Comment by clemsos** [comment]
here r is a standard request answer from the requests Python lib

**Comment by clemsos** [comment]
data may contain a single result or a list depending on the API call.

**Comment by clemsos** [comment]
you can also define topogram_id manually using the ID in the URL

**Comment by clemsos** [comment]
should be fixed now
